name: Conditional CI Pipeline

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
  pull_request: #in case i need to work with a team or if i need to have a code review before merging
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'

jobs:
  code-changes:
    name: Run Tests on Code Changes
    if: |
      contains(github.event.head_commit.message, 'src/') ||
      contains(github.event.head_commit.message, 'public/') ||
      contains(github.event.head_commit.message, 'package.json') ||
      contains(github.event.head_commit.message, 'package-lock.json')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Run Tests
        run: |
          npm ci
          npm run test -- --watchAll=false

  dockerfile-changes:
    name: Build & Push Docker Image on Dockerfile Changes
    if: |
      contains(github.event.head_commit.message, 'Dockerfile')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: manarmagdi96/my-portfolio:latest
