name: Conditional CI Pipeline

on:
  workflow_dispatch
jobs:
  code-changes:
    name: Run Tests on Code Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Run Tests
        continue-on-error: true
        run: |
          npm ci
          npm run test -- --watchAll=false

  dockerfile-changes:
    name: Build & Push Docker Image on Dockerfile Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: manarmagdi96/my-portfolio:latest
